apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        # image: gcr.io/{{PROJECT_ID}}/service-a:v1
        image: gcr.io/observability-277802/service-a:v1
        ports:
          - containerPort: 8001
            protocol: TCP
        env:
          - name: SERVICE_HOST
            value: "service-b"
          - name: SERVICE_PORT
            value: "8002"
        readinessProbe:
          httpGet:
            port: 8001
            path: /
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 5
          failureThreshold: 20
        livenessProbe:
          httpGet:
            port: 8001
            path: /
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 4
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 40
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---

apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  type: ClusterIP
  selector:
    app: service-a
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
